		

		</div>
		<div id="footer">
			<ul>
				<li><a href="sitemap.php">Site Map</a><li>
				<li><a href="index.php">Home</a><li>
				<li><a href="teaching.php">Teaching</a><li>
				<li><a href="about.php">About Us</a><li>
				<li><a href="faq.php">FAQ</a><li>
				<li><a href="contact.php">Contact Us</a><li>
			</ul>
			<p>Copyright 2016 Pinelands Music School. ALL RIGHTS RESERVED | Phone: (07) 3298 1487 | Email: hello@parklandsmusicschool.com.au | 24 Parklands Road, Sunnybank QLD 4109</p>
		</div>
	</body>
</html>