		<footer id="footer">
			<div class="container">
				<div class="row">


					<div class="col-sm-3">
						<ul>
							<!--<li><a href="./sitemap.php">Site Map</a></li>-->
							<li><a href="./index.php">Home</a></li>
							<li><a href="./teachers.php">Teachers</a></li>
							<li><a href="./about.php">About Us</a></li>
							<li><a href="./faq.php">FAQ</a></li>
							<li><a href="./contact.php">Contact Us</a></li>
						</ul>
					</div>

					<div class="col-sm-5">
						<ul>
							<li><i class="fa fa-phone" aria-hidden="true"></i> (07) 3298 1487</li>
							<li><i class="fa fa-envelope" aria-hidden="true"></i></i> hello@pinelandsmusicschool.com.au</li>
							<li><i class="fa fa-map-marker" aria-hidden="true"></i> 24 Pinelands Road, Sunnybank QLD 4109</li>
						</ul>
					</div>

					<div class="col-sm-4">
						<p>Copyright 2016 Pinelands Music School. ALL RIGHTS RESERVED</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- JS -->
		<script type="text/javascript" src="js/jquery.min.js"></script><!-- jQuery -->
		<script type="text/javascript" src="js/bootstrap.min.js"></script><!-- Bootstrap -->
		<script type="text/javascript" src="js/jquery.parallax.js"></script><!-- Parallax -->
		<script type="text/javascript" src="js/smoothscroll.js"></script><!-- Smooth Scroll -->
		<script type="text/javascript" src="js/masonry.pkgd.min.js"></script><!-- masonry -->
		<script type="text/javascript" src="js/jquery.fitvids.js"></script><!-- fitvids -->
		<script type="text/javascript" src="js/owl.carousel.min.js"></script><!-- Owl-Carousel -->
		<script type="text/javascript" src="js/jquery.counterup.min.js"></script><!-- CounterUp -->
		<script type="text/javascript" src="js/waypoints.min.js"></script><!-- CounterUp -->
		<script type="text/javascript" src="js/jquery.isotope.min.js"></script><!-- isotope -->
		<script type="text/javascript" src="js/jquery.magnific-popup.min.js"></script><!-- magnific-popup -->
		<script type="text/javascript" src="js/scripts.js"></script><!-- Scripts -->

	</body>
</html>